services:
  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./fast-graphql
    environment:
      DB_USER: user
      DB_PASSWORD: 1234
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: biblioteca
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./fast-graphql:/app

  frontend:
    build: ./svelte-graphql
    environment:
      PUBLIC_API_URL: http://localhost:8000/graphql
      PUBLIC_INTERNAL_API_URL: http://backend:8000/graphql
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data: